site_name: 'iupred'
site_url: https://saezlab.github.io/iupred
theme:
    name: material
    font:
        text: Lato
        code: Roboto Mono
    features:
    -   content.code.copy
    -   content.action.edit
    -   navigation.instant
    -   navigation.footer
    palette:
    -   scheme: default
        primary: teal
        accent: light blue
        toggle:
            icon: material/toggle-switch
            name: Switch to dark mode
    -   scheme: slate
        primary: teal
        accent: light blue
        toggle:
            icon: material/toggle-switch-off
            name: Switch to light mode

nav:
-   Home: index.md
-   Tutorials:
    -   Single Sequence: tutorials/single_sequence.md
    -   Batch Prediction: tutorials/batch_prediction.md
    -   Low-Memory Mode: tutorials/low_memory.md
-   Reference: reference.md

#=======    Extension settings (sorted alphabetically)  =====
markdown_extensions:
-   admonition
-   attr_list
-   md_in_html
-   toc:
        permalink: true
  #----- Python Markdown Extensions
-   pymdownx.details
-   pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
-   pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
-   pymdownx.inlinehilite
-   pymdownx.snippets
-   pymdownx.superfences:
        custom_fences:
        -   name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
-   pymdownx.tabbed:
        alternate_style: true

#=======    Plugins    =====
plugins:
-   search
-   mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    annotations_path: brief
                    docstring_style: google
                    heading_level: 3
                    members_order: source
                    modernize_annotations: true
                    show_category_heading: true
                    show_object_full_path: false
                    show_root_heading: true
                    show_root_toc_entry: true
                    show_signature: true
                    show_signature_annotations: true
                    show_source: false
                    signature_crossrefs: true

copyright: Â© Copyright 2021-2026, ELTE / Saez-lab.
